const DATA_VERSION = 2;
const KEYS = { version:'oneupDataVersion', points:'oneupPoints', history:'oneupDailyHistory', profile:'oneupProfile', settings:'oneupSettings', activitySettings:'oneupActivitySettingsV2', activityLog:'oneupActivityLogV2', archivedVillage:'oneupArchivedVillageDataV2' };
const oldVillageKeys = ['oneupVillageResidents','oneupMissions','oneupStepBank'];
const activities = {
  steps:{icon:'👟',name:'Skridt',unit:'skridt',goal:8000,period:'day',enabled:true,auto:false}, sleep:{icon:'🌙',name:'Søvn',unit:'timer',goal:8,period:'day',enabled:false,auto:true}, breathing:{icon:'🫁',name:'Åndedræt',unit:'runder',goal:5,period:'day',enabled:true,auto:false}, meditation:{icon:'🧘',name:'Meditation',unit:'min',goal:10,period:'day',enabled:false,auto:true}, strength:{icon:'💪',name:'Styrketræning',unit:'pas',goal:3,period:'week',enabled:false,auto:true}, running:{icon:'🏃',name:'Løb',unit:'min',goal:60,period:'week',enabled:false,auto:true}, cycling:{icon:'🚲',name:'Cykling',unit:'min',goal:120,period:'week',enabled:false,auto:true}, screenfree:{icon:'📵',name:'Skærmfri tid før sengetid',unit:'min',goal:30,period:'day',enabled:false,auto:true}, socialfree:{icon:'💬',name:'Tid uden sociale medier',unit:'min',goal:60,period:'day',enabled:false,auto:true}
};
const $ = s => document.querySelector(s); const $$ = s => Array.from(document.querySelectorAll(s));
const todayKey = () => (window.__oneUpNow ? window.__oneUpNow() : new Date()).toISOString().slice(0,10);
const day = (offset=0, base=todayKey()) => { const d=new Date(`${base}T12:00:00Z`); d.setUTCDate(d.getUTCDate()+offset); return d.toISOString().slice(0,10); };
const num = v => Math.max(0, Number(v)||0); const fmt = v => Math.round(v).toLocaleString('da-DK');
const read = (k,f) => { try { return JSON.parse(localStorage.getItem(k)) ?? f; } catch { return f; } }; const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let state;
function defaultActivitySettings(){return Object.fromEntries(Object.entries(activities).map(([id,a])=>[id,{enabled:a.enabled,goal:a.goal,front:true}]))}
function migrateData(){
  if (Number(localStorage.getItem(KEYS.version)||0) >= DATA_VERSION) return;
  const archived={}; oldVillageKeys.forEach(k=>{ const v=localStorage.getItem(k); if(v!==null){ archived[k]=v; localStorage.removeItem(k); }});
  if(Object.keys(archived).length) save(KEYS.archivedVillage, archived);
  const oldLog = read('oneupActivityLogV1', []); if(oldLog.length && !localStorage.getItem(KEYS.activityLog)) save(KEYS.activityLog, oldLog);
  const oldSettings = read('oneupActivitySettingsV1', null); if(oldSettings && !localStorage.getItem(KEYS.activitySettings)){ const next=defaultActivitySettings(); Object.entries(oldSettings).forEach(([id,v])=>{ if(next[id]) next[id]={...next[id],...v,goal:num(v.goal?.amount ?? v.goal ?? next[id].goal)}; }); save(KEYS.activitySettings,next); }
  localStorage.setItem(KEYS.version, String(DATA_VERSION));
}
function loadState(){ migrateData(); state={ points:num(localStorage.getItem(KEYS.points)), history:read(KEYS.history,{}), profile:read(KEYS.profile,{}), settings:{vibration:false,sounds:false,voice:false,weekStarts:'monday',units:'metric',language:'da',...(read(KEYS.settings,{})||{})}, activitySettings:read(KEYS.activitySettings, defaultActivitySettings()), log:read(KEYS.activityLog,[]) }; ensureToday(); }
function persist(){ localStorage.setItem(KEYS.points,String(Math.round(state.points))); save(KEYS.history,state.history); save(KEYS.profile,state.profile); save(KEYS.settings,state.settings); save(KEYS.activitySettings,state.activitySettings); save(KEYS.activityLog,state.log); }
function ensureToday(){ const t=todayKey(); state.history[t] ||= {date:t,entries:[],activityPoints:{},totalPoints:0,oneUpScore:0,steps:0,boxBreathingCount:0,breathing478Count:0}; }
function entries(date=todayKey(), id=null){ return state.log.filter(e=>e.date===date && (!id || e.activity===id)); }
function valueFor(id,date=todayKey()){ const es=entries(date,id); if(id==='steps') return es.at(-1)?.value || state.history[date]?.steps || 0; if(id==='sleep') return es.reduce((s,e)=>s+num(e.hours),0); if(id==='socialfree' && es.at(-1)?.mode==='usage') return Math.max(0, state.activitySettings[id].goal - es.at(-1).value); return es.reduce((s,e)=>s+num(e.value),0); }
function goalFor(id){ return num(state.activitySettings[id]?.goal ?? activities[id].goal); }
function periodValue(id,date=todayKey()){ if(activities[id].period==='day') return valueFor(id,date); return [0,-1,-2,-3,-4,-5,-6].reduce((s,o)=>s+valueFor(id,day(o,date)),0); }
function activityPercent(id,date=todayKey()){ return goalFor(id) ? Math.min(100, periodValue(id,date)/goalFor(id)*100) : 0; }
function pointsForEntry(e){ const g=goalFor(e.activity); if(e.activity==='steps') return Math.floor(num(e.value)/100); if(e.activity==='breathing') return num(e.value)*5; if(e.activity==='meditation') return Math.min(30,num(e.value)); if(e.activity==='strength') return 20; if(e.activity==='running') return Math.min(60,num(e.value))*2; if(e.activity==='cycling') return Math.min(60,num(e.value)); if(e.activity==='sleep') return num(e.hours)>=g?20:0; if(e.activity==='screenfree') return num(e.value)>=g?15:0; if(e.activity==='socialfree') return (e.mode==='usage'?num(e.value)<=g:num(e.value)>=g)?15:0; return 0; }
function recalc(){ Object.values(state.history).forEach(r=>{ r.activityPoints={}; r.totalPoints=0; }); state.log.forEach(e=>{ const r=state.history[e.date] ||= {date:e.date,entries:[],activityPoints:{},totalPoints:0}; const p=pointsForEntry(e); r.activityPoints[e.activity]=(r.activityPoints[e.activity]||0)+p; }); Object.entries(state.history).forEach(([date,r])=>{ r.steps=valueFor('steps',date); r.boxBreathingCount=entries(date,'breathing').filter(e=>e.mode==='box').reduce((s,e)=>s+num(e.value),0); r.breathing478Count=entries(date,'breathing').filter(e=>e.mode==='478').reduce((s,e)=>s+num(e.value),0); r.totalPoints=Object.values(r.activityPoints||{}).reduce((a,b)=>a+num(b),0); r.oneUpScore=oneUpScore(date); }); state.points=Object.values(state.history).reduce((s,r)=>s+num(r.totalPoints),0); persist(); }
function oneUpScore(date=todayKey()){ const enabled=Object.keys(activities).filter(id=>state.activitySettings[id]?.enabled); if(!enabled.length) return 0; return Math.round(enabled.reduce((s,id)=>s+activityPercent(id,date),0)/enabled.length); }
function streak(){ let c=0; for(let i=0;i<365;i++){ if(oneUpScore(day(-i))>0) c++; else break; } return c; }
function bestStreak(){ let best=0,cur=0; Object.keys(state.history).sort().forEach(d=>{ cur=oneUpScore(d)>0?cur+1:0; best=Math.max(best,cur); }); return best; }
function addEntry(activity, data){ const e={id:`${Date.now()}-${Math.random().toString(16).slice(2)}`,date:todayKey(),activity,...data}; if(activity==='steps') state.log=state.log.filter(x=>!(x.date===e.date&&x.activity==='steps')); state.log.push(e); recalc(); render(); }
function deleteEntry(id){ state.log=state.log.filter(e=>e.id!==id); recalc(); render(); }
function editEntry(id){ const e=state.log.find(x=>x.id===id); if(!e) return; const v=prompt('Ny værdi', e.value ?? e.hours ?? 0); if(v===null) return; if(e.activity==='sleep') e.hours=num(v); else e.value=num(v); recalc(); render(); }
function compareLastWeek(id){ const now=periodValue(id), last=periodValue(id,day(-7)); if(!last && !now) return 'Ingen sammenligning endnu'; const pct= last ? Math.round((now-last)/last*100) : 100; return pct>=0?`+${pct}% mod sidste uge`:`${pct}% mod sidste uge`; }
function renderToday(){ const score=oneUpScore(); $('#oneup-score').textContent=score; $('#today-points').textContent=fmt(state.history[todayKey()].totalPoints); $('#header-points').textContent=fmt(state.points); const enabled=Object.keys(activities).filter(id=>state.activitySettings[id]?.enabled); $('#goals-met').textContent=`${enabled.filter(id=>activityPercent(id)>=100).length}/${enabled.length}`; $('#today-streak').textContent=`${streak()} dage`; $('#encouragement').textContent= score>=90?'Du har allerede slået stærkt igennem i dag.':score>=60?'Du er godt i gang – hold rytmen roligt.':'Start med én lille handling. Det tæller.'; $('#today-activity-cards').innerHTML=enabled.map(activityCard).join(''); }
function activityCard(id){ const a=activities[id], v=periodValue(id), g=goalFor(id), pct=activityPercent(id), pts=state.history[todayKey()].activityPoints?.[id]||0; return `<article class="card activity"><div class="card-head"><h3>${a.icon} ${a.name}</h3><strong>${Math.round(pct)}%</strong></div><p class="big">${fmt(v)} ${a.unit}</p><p>Mål: ${fmt(g)} ${a.unit}${a.period==='week'?' pr. uge':''}</p><div class="progress"><span style="width:${pct}%"></span></div><p>${fmt(pts)} point i dag · ${compareLastWeek(id)}</p><button data-quick="${id}">Registrér / redigér</button></article>`; }
function renderActivities(){ $('#activity-manager').innerHTML=Object.entries(activities).map(([id,a])=>`<article class="card"><div class="card-head"><h3>${a.icon} ${a.name}</h3><label class="switch"><input data-toggle="${id}" type="checkbox" ${state.activitySettings[id]?.enabled?'checked':''}/> Aktiv</label></div><p>I dag: ${fmt(valueFor(id))} ${a.unit}</p><label class="field">Personligt mål<input data-goal="${id}" type="number" value="${goalFor(id)}" /></label>${a.auto?'<p class="muted">Automatisk registrering kommer senere.</p>':''}<div class="entry-controls">${entryControls(id)}</div></article>`).join(''); renderEntryList(); }
function entryControls(id){ if(id==='sleep') return '<input data-sleep-start type="time" value="22:30"><input data-sleep-end type="time" value="06:30"><button data-add="sleep">Registrér søvn</button>'; if(id==='meditation') return '<button data-add="meditation" data-value="5">5</button><button data-add="meditation" data-value="10">10</button><button data-add="meditation" data-value="20">20</button><input data-input="meditation" type="number" placeholder="Min"><button data-add="meditation">Gem</button>'; if(id==='running'||id==='cycling') return `<input data-input="${id}" type="number" placeholder="Minutter"><input data-distance="${id}" type="number" placeholder="Distance valgfri"><button data-add="${id}">Gem</button>`; return `<input data-input="${id}" type="number" placeholder="${activities[id].unit}"><button data-add="${id}">Gem</button>`; }
function renderEntryList(){ $('#entry-list').innerHTML=entries().map(e=>`<li>${activities[e.activity].name}: ${fmt(e.value??e.hours)} ${activities[e.activity].unit} <button data-edit-entry="${e.id}">Ret</button> <button data-delete-entry="${e.id}">Slet</button></li>`).join('')||'<li>Ingen registreringer i dag endnu.</li>'; }
function renderCompetition(){ const type=$('#competition-type'); if(!type.options.length) ['Procent af personligt mål','Samlede point','Skridt','Søvnregularitet','Åndedrætsrunder','Skærmfri aftener','Forbedring fra egen baseline'].forEach(x=>type.add(new Option(x,x))); const rows=[['Dig',oneUpScore(),'+8',true],['Amina',86,'+4',true],['Jonas',78,'-2',false],['Sofie',71,'+11',true]]; $('#leaderboard').innerHTML=rows.sort((a,b)=>b[1]-a[1]).map((r,i)=>`<li><b>${i+1}. ${r[0]}</b><span>${r[1]} · ${r[3]?'↗':'↘'} ${r[2]}</span></li>`).join(''); const s=streak(); $('#self-summary').innerHTML=[`Denne uge mod sidste uge: ${compareLastWeek('steps')}`,`Målopfyldelse: ${oneUpScore()}%`,`Personlige rekorder: ${Math.max(...Object.values(state.history).map(r=>num(r.oneUpScore)),0)}`,`Aktive dage: ${Object.values(state.history).filter(r=>num(r.totalPoints)>0).length}`,`Nuværende streak: ${s}`,`Længste streak: ${bestStreak()}`,`Bedste uge: ${weeklyScores()[0]||0} point`,`Denne uge er din 2. bedste uge ud af de seneste 8 uger.`].map(t=>`<article class="card">${t}</article>`).join(''); $('#self-ranking').innerHTML=Object.keys(activities).slice(0,4).map((id,i)=>`<li><b>${i+1}. ${activities[id].name}</b><span>${100+i*5}% af sidste uge</span></li>`).join(''); }
function weeklyScores(){ return [0,1,2,3,4,5,6,7].map(w=>[0,1,2,3,4,5,6].reduce((s,d)=>s+num(state.history[day(-(w*7+d))]?.totalPoints),0)).sort((a,b)=>b-a); }
function renderDevelopment(){ const filter=$('#development-filter'); if(filter.options.length===1) Object.entries(activities).forEach(([id,a])=>filter.add(new Option(a.name,id))); $('#bars-7').innerHTML=[-6,-5,-4,-3,-2,-1,0].map(o=>{const d=day(o), val=filter.value==='all'?oneUpScore(d):activityPercent(filter.value,d); return `<div><span style="height:${val}%"></span><small>${d.slice(5)}</small></div>`}).join(''); $('#bars-4').innerHTML=[3,2,1,0].map(w=>`<div><span style="height:${Math.min(100,weeklyScores()[w]||0)}%"></span><small>Uge ${4-w}</small></div>`).join(''); $('#weekly-summary').innerHTML=['Stærkeste aktivitet: Skridt','Største forbedring: Søvnregularitet','Mest potentiale: Skærmfri tid','Nåede mål: '+$('#goals-met').textContent,'Samlet ændring: Du er lidt under sidste uge, men stadig godt i gang.'].map(t=>`<article class="card">${t}</article>`).join(''); }
function renderProfile(){ const fields=[['nickname','Navn eller kaldenavn','text'],['birthYear','Fødselsår','number'],['height','Højde','number'],['weight','Vægt','number'],['sex','Biologisk køn','text'],['country','Bopælsland','text'],['language','Sprog','text'],['units','Enheder','text']]; $('#profile-form').innerHTML=fields.map(([k,l,t])=>`<label class="field">${l}<input name="${k}" type="${t}" value="${state.profile[k]||''}"></label>`).join('')+'<button>Gem profil</button>'; $('#settings-form').innerHTML=['vibration','sounds','voice'].map(k=>`<label><input data-setting="${k}" type="checkbox" ${state.settings[k]?'checked':''}> ${k}</label>`).join('')+'<label class="field">Uge starter<select data-setting="weekStarts"><option value="monday">Mandag</option><option value="sunday">Søndag</option></select></label>'; }
function render(){ recalcSilently(); renderToday(); renderActivities(); renderCompetition(); renderDevelopment(); renderProfile(); bindDynamic(); }
function recalcSilently(){ const old=persist; Object.values(state.history).forEach(r=>{r.activityPoints={};r.totalPoints=0}); state.log.forEach(e=>{const r=state.history[e.date] ||= {date:e.date,activityPoints:{}}; const p=pointsForEntry(e); r.activityPoints[e.activity]=(r.activityPoints[e.activity]||0)+p;}); Object.entries(state.history).forEach(([d,r])=>{r.totalPoints=Object.values(r.activityPoints||{}).reduce((s,v)=>s+num(v),0); r.oneUpScore=oneUpScore(d);}); state.points=Object.values(state.history).reduce((s,r)=>s+num(r.totalPoints),0); }
function bindDynamic(){ $$('[data-toggle]').forEach(el=>el.onchange=()=>{state.activitySettings[el.dataset.toggle].enabled=el.checked; persist(); render();}); $$('[data-goal]').forEach(el=>el.onchange=()=>{state.activitySettings[el.dataset.goal].goal=num(el.value); persist(); render();}); $$('[data-add]').forEach(b=>b.onclick=()=>manualAdd(b.dataset.add,b)); $$('[data-quick]').forEach(b=>b.onclick=()=>showPage('activities')); $$('[data-delete-entry]').forEach(b=>b.onclick=()=>deleteEntry(b.dataset.deleteEntry)); $$('[data-edit-entry]').forEach(b=>b.onclick=()=>editEntry(b.dataset.editEntry)); }
function manualAdd(id,b){ if(id==='sleep'){ const [sh,sm]=$('[data-sleep-start]').value.split(':').map(Number), [eh,em]=$('[data-sleep-end]').value.split(':').map(Number); let h=(eh+em/60)-(sh+sm/60); if(h<0) h+=24; addEntry(id,{value:h,hours:h,start:$('[data-sleep-start]').value,end:$('[data-sleep-end]').value}); return; } const input=$(`[data-input="${id}"]`); addEntry(id,{value:num(b.dataset.value ?? input?.value), distance:num($(`[data-distance="${id}"]`)?.value), mode:id==='breathing'?document.querySelector('input[name="breathing-mode"]:checked')?.value:undefined}); }
function showPage(id){ $$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===id)); $$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id)); }
function bindStatic(){ $$('[data-nav]').forEach(b=>b.onclick=()=>showPage(b.dataset.nav)); $$('[data-competition]').forEach(b=>b.onclick=()=>{ $$('[data-competition]').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $('#competition-others').hidden=b.dataset.competition!=='others'; $('#competition-self').hidden=b.dataset.competition!=='self';}); $('#create-group').onclick=()=>$('#group-message').textContent='Rigtige grupper og invitationer kræver login og kommer i en senere version.'; $('#profile-form').onsubmit=e=>{e.preventDefault(); new FormData(e.target).forEach((v,k)=>state.profile[k]=v); persist();}; $('#development-filter').onchange=renderDevelopment; $('#start-breathing').onclick=()=>{ window.breathingTimer=setInterval(()=>addEntry('breathing',{value:1,mode:document.querySelector('input[name="breathing-mode"]:checked')?.value||'box'}), 3000); $('#breathing-label').textContent='Kører';}; $('#stop-breathing').onclick=()=>{clearInterval(window.breathingTimer); $('#breathing-label').textContent='Stoppet';}; }
loadState(); bindStatic(); render(); showPage('today');
if (typeof window !== 'undefined') window.__oneUpTest = { get state(){ return state; }, recalc, oneUpScore, pointsForEntry, activities };
if (typeof module !== 'undefined') module.exports={activities,loadState,oneUpScore,pointsForEntry};
