const DATA_VERSION = 2;
const STREAK_DATA_VERSION = 1;
const KEYS = { version:'oneupDataVersion', points:'oneupPoints', history:'oneupDailyHistory', profile:'oneupProfile', settings:'oneupSettings', activitySettings:'oneupActivitySettingsV2', activityLog:'oneupActivityLogV2', archivedVillage:'oneupArchivedVillageDataV2', streak:'oneupStreakDataV1' };
const oldVillageKeys = ['oneupVillageResidents','oneupMissions','oneupStepBank'];
const activities = {
  steps:{icon:'👟',name:'Skridt',unit:'skridt',goal:8000,period:'day',enabled:true,auto:false}, sleep:{icon:'🌙',name:'Søvn',unit:'timer',goal:8,period:'day',enabled:false,auto:true}, breathing:{icon:'🫁',name:'Åndedræt',unit:'runder',goal:5,period:'day',enabled:true,auto:false}, meditation:{icon:'🧘',name:'Meditation',unit:'min',goal:10,period:'day',enabled:false,auto:true}, strength:{icon:'💪',name:'Styrketræning',unit:'pas',goal:3,period:'week',enabled:false,auto:true}, running:{icon:'🏃',name:'Løb',unit:'min',goal:60,period:'week',enabled:false,auto:true}, cycling:{icon:'🚲',name:'Cykling',unit:'min',goal:120,period:'week',enabled:false,auto:true}, screenfree:{icon:'📵',name:'Skærmfri tid før sengetid',unit:'min',goal:30,period:'day',enabled:false,auto:true}, socialfree:{icon:'💬',name:'Tid uden sociale medier',unit:'min',goal:60,period:'day',enabled:false,auto:true}
};
const streakDefaults = { sleep:6, meditation:5, breathing:5, steps:5, screenfree:5, socialfree:5, strength:3, running:3, cycling:3 };
const focusActivities = ['sleep','meditation','breathing'];
const $ = s => document.querySelector(s); const $$ = s => Array.from(document.querySelectorAll(s));
const todayKey = () => (window.__oneUpNow ? window.__oneUpNow() : new Date()).toISOString().slice(0,10);
const day = (offset=0, base=todayKey()) => { const d=new Date(`${base}T12:00:00Z`); d.setUTCDate(d.getUTCDate()+offset); return d.toISOString().slice(0,10); };
const num = v => Math.max(0, Number(v)||0); const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,v)); const fmt = v => Math.round(v).toLocaleString('da-DK');
const read = (k,f) => { try { return JSON.parse(localStorage.getItem(k)) ?? f; } catch { return f; } }; const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let state;
function defaultActivitySettings(){return Object.fromEntries(Object.entries(activities).map(([id,a])=>[id,{enabled:a.enabled,goal:a.goal,front:true,streakEnabled:['sleep','meditation','breathing','steps','screenfree','socialfree'].includes(id),dailyRequirement:a.goal,weeklyGoal:streakDefaults[id]||5,autoProtection:true,protectionEnabled:true,sleepCriteria:{duration:true,interval:false,bedtime:false,wake:false,screenfree:false},sleepMinHours:a.goal,sleepMinTolerance:0,sleepMinInterval:7,sleepMaxInterval:9,bedtimeTarget:'22:30',bedtimeTolerance:30,wakeTarget:'06:30',wakeTolerance:30}]))}
function normalizeSettings(){ const def=defaultActivitySettings(); Object.keys(activities).forEach(id=>{ state.activitySettings[id]={...def[id],...(state.activitySettings[id]||{})}; if(state.activitySettings[id].dailyRequirement==null) state.activitySettings[id].dailyRequirement=state.activitySettings[id].goal; if(state.activitySettings[id].weeklyGoal==null) state.activitySettings[id].weeklyGoal=streakDefaults[id]||5; }); }
function migrateData(){
  if (Number(localStorage.getItem(KEYS.version)||0) >= DATA_VERSION) return;
  const archived={}; oldVillageKeys.forEach(k=>{ const v=localStorage.getItem(k); if(v!==null){ archived[k]=v; localStorage.removeItem(k); }});
  if(Object.keys(archived).length) save(KEYS.archivedVillage, archived);
  const oldLog = read('oneupActivityLogV1', []); if(oldLog.length && !localStorage.getItem(KEYS.activityLog)) save(KEYS.activityLog, oldLog);
  const oldSettings = read('oneupActivitySettingsV1', null); if(oldSettings && !localStorage.getItem(KEYS.activitySettings)){ const next=defaultActivitySettings(); Object.entries(oldSettings).forEach(([id,v])=>{ if(next[id]) next[id]={...next[id],...v,goal:num(v.goal?.amount ?? v.goal ?? next[id].goal)}; }); save(KEYS.activitySettings,next); }
  localStorage.setItem(KEYS.version, String(DATA_VERSION));
}
function loadState(){ migrateData(); state={ points:num(localStorage.getItem(KEYS.points)), history:read(KEYS.history,{}), profile:read(KEYS.profile,{}), settings:{vibration:false,sounds:false,voice:false,weekStarts:'monday',units:'metric',language:'da',...(read(KEYS.settings,{})||{})}, activitySettings:read(KEYS.activitySettings, defaultActivitySettings()), log:read(KEYS.activityLog,[]), streakData:read(KEYS.streak,{version:STREAK_DATA_VERSION,manualProtection:{}}) }; normalizeSettings(); ensureToday(); }
function persist(){ localStorage.setItem(KEYS.points,String(Math.round(state.points))); save(KEYS.history,state.history); save(KEYS.profile,state.profile); save(KEYS.settings,state.settings); save(KEYS.activitySettings,state.activitySettings); save(KEYS.activityLog,state.log); save(KEYS.streak,{version:STREAK_DATA_VERSION,manualProtection:state.streakData.manualProtection||{},summary:buildStreakSummary()}); }
function ensureToday(){ const t=todayKey(); state.history[t] ||= {date:t,entries:[],activityPoints:{},totalPoints:0,oneUpScore:0,steps:0,boxBreathingCount:0,breathing478Count:0}; }
function effectiveDate(e){ if(e.activity!=='sleep') return e.date; if(e.sleepDate) return e.sleepDate; if(e.end && e.start && e.end < e.start) return e.date; return e.date; }
function entries(date=todayKey(), id=null){ return state.log.filter(e=>effectiveDate(e)===date && (!id || e.activity===id)); }
function valueFor(id,date=todayKey()){ const es=entries(date,id); if(id==='steps') return es.at(-1)?.value || state.history[date]?.steps || 0; if(id==='sleep') return es.reduce((s,e)=>s+num(e.hours),0); if(id==='socialfree' && es.at(-1)?.mode==='usage') return Math.max(0, state.activitySettings[id].goal - es.at(-1).value); return es.reduce((s,e)=>s+num(e.value),0); }
function goalFor(id){ return num(state.activitySettings[id]?.goal ?? activities[id].goal); }
function dailyRequirementFor(id){ return num(state.activitySettings[id]?.dailyRequirement ?? goalFor(id)); }
function periodValue(id,date=todayKey()){ if(activities[id].period==='day') return valueFor(id,date); return [0,-1,-2,-3,-4,-5,-6].reduce((s,o)=>s+valueFor(id,day(o,date)),0); }
function activityPercent(id,date=todayKey()){ return goalFor(id) ? Math.min(100, periodValue(id,date)/goalFor(id)*100) : 0; }
function pointsForEntry(e){ const g=goalFor(e.activity); if(e.activity==='steps') return Math.floor(num(e.value)/100); if(e.activity==='breathing') return num(e.value)*5; if(e.activity==='meditation') return Math.min(30,num(e.value)); if(e.activity==='strength') return 20; if(e.activity==='running') return Math.min(60,num(e.value))*2; if(e.activity==='cycling') return Math.min(60,num(e.value)); if(e.activity==='sleep') return num(e.hours)>=g?20:0; if(e.activity==='screenfree') return num(e.value)>=g?15:0; if(e.activity==='socialfree') return (e.mode==='usage'?num(e.value)<=g:num(e.value)>=g)?15:0; return 0; }
function minutes(t){ const [h,m]=(t||'00:00').split(':').map(Number); return h*60+m; }
function withinTime(value,target,tol){ const diff=Math.abs(((minutes(value)-minutes(target)+720+1440)%1440)-720); return diff<=num(tol); }
function sleepMet(date){ const s=state.activitySettings.sleep, es=entries(date,'sleep'), hours=valueFor('sleep',date); if(!es.length) return false; const checks=[]; if(s.sleepCriteria?.duration) checks.push(hours+num(s.sleepMinTolerance||0)>=num(s.sleepMinHours||dailyRequirementFor('sleep'))); if(s.sleepCriteria?.interval) checks.push(hours>=num(s.sleepMinInterval||7)&&hours<=num(s.sleepMaxInterval||9)); if(s.sleepCriteria?.bedtime) checks.push(es.some(e=>withinTime(e.start,s.bedtimeTarget,s.bedtimeTolerance))); if(s.sleepCriteria?.wake) checks.push(es.some(e=>withinTime(e.end,s.wakeTarget,s.wakeTolerance))); if(s.sleepCriteria?.screenfree) checks.push(requirementMet('screenfree',date)); return checks.length?checks.every(Boolean):hours>=dailyRequirementFor('sleep'); }
function requirementMet(id,date=todayKey()){ if(!state.activitySettings[id]?.streakEnabled) return false; if(id==='sleep') return sleepMet(date); if(id==='socialfree') { const es=entries(date,id); if(es.at(-1)?.mode==='usage') return num(es.at(-1).value)<=dailyRequirementFor(id); } return valueFor(id,date)>=dailyRequirementFor(id); }
function protectionUsed(id,date){ return !!state.streakData.manualProtection?.[id]?.[date]; }
function canProtect(id,date){ const s=state.activitySettings[id]; if(!s?.protectionEnabled) return false; if(requirementMet(id,date)) return false; if(protectionUsed(id,day(-1,date))||protectionUsed(id,day(1,date))) return false; const used14=[...Array(27)].some((_,i)=>protectionUsed(id,day(i-13,date))); return !used14; }
function maybeAutoProtect(id,date){ const s=state.activitySettings[id]; if(s?.autoProtection && canProtect(id,date)){ state.streakData.manualProtection[id] ||= {}; state.streakData.manualProtection[id][date]=true; return true; } return false; }
function dayComplete(id,date=todayKey(), useAuto=false){ if(requirementMet(id,date)) return true; if(protectionUsed(id,date)) return true; if(useAuto && maybeAutoProtect(id,date)) return true; return false; }
function allDates(){ const dates=new Set(Object.keys(state.history)); state.log.forEach(e=>dates.add(effectiveDate(e))); dates.add(todayKey()); return [...dates].sort(); }
function streakInfo(id,date=todayKey()){ let current=0; for(let i=0;i<730;i++){ if(dayComplete(id,day(-i,date), true)) current++; else break; } let best=0,cur=0,last=null; allDates().forEach(d=>{ if(dayComplete(id,d)){ cur++; last=d; } else cur=0; best=Math.max(best,cur); }); return {id,current,best,lastActiveDate:last,metToday:requirementMet(id,date),protectedToday:protectionUsed(id,date),completeToday:dayComplete(id,date),weekly:weeklyConsistency(id,date)}; }
function enabledStreakIds(){ return Object.keys(activities).filter(id=>state.activitySettings[id]?.enabled && state.activitySettings[id]?.streakEnabled); }
function weekStart(date=todayKey()){ const d=new Date(`${date}T12:00:00Z`), dow=d.getUTCDay(), off=state.settings.weekStarts==='sunday'?dow:(dow+6)%7; d.setUTCDate(d.getUTCDate()-off); return d.toISOString().slice(0,10); }
function weekDates(date=todayKey()){ const s=weekStart(date); return [0,1,2,3,4,5,6].map(i=>day(i,s)); }
function weeklyConsistency(id,date=todayKey()){ const dates=weekDates(date), done=dates.filter(d=>dayComplete(id,d)).length, goal=clamp(num(state.activitySettings[id]?.weeklyGoal||5),1,7), elapsed=dates.findIndex(d=>d===date)+1 || 7; return {done,goal,percent:Math.round(done/goal*100),onTrack:done>=Math.ceil(goal*elapsed/7),dates}; }
function activityWeights(ids){ const activeFocus=ids.filter(id=>focusActivities.includes(id)), other=ids.filter(id=>!focusActivities.includes(id)), w={}; if(activeFocus.length&&other.length){ activeFocus.forEach(id=>w[id]=0.60/activeFocus.length); other.forEach(id=>w[id]=0.40/other.length); } else ids.forEach(id=>w[id]=1/ids.length); return w; }
function consistencyScore(date=todayKey()){ const ids=enabledStreakIds(); if(!ids.length) return 0; const weights=activityWeights(ids); let daily=0,weekly=0,stability=0; ids.forEach(id=>{ daily+=(dayComplete(id,date)?100:0)*weights[id]; weekly+=clamp(weeklyConsistency(id,date).percent)*weights[id]; const days=[...Array(28)].filter((_,i)=>dayComplete(id,day(-i,date))).length; stability+=(days/28*100)*weights[id]; }); return Math.round(daily*.35+weekly*.35+stability*.30); }
function buildStreakSummary(date=todayKey()){ const ids=enabledStreakIds(), infos=Object.fromEntries(ids.map(id=>[id,streakInfo(id,date)])); return {score:consistencyScore(date),activities:infos}; }
function recalc(){ Object.values(state.history).forEach(r=>{ r.activityPoints={}; r.totalPoints=0; }); state.log.forEach(e=>{ const d=effectiveDate(e); const r=state.history[d] ||= {date:d,entries:[],activityPoints:{},totalPoints:0}; const p=pointsForEntry(e); r.activityPoints[e.activity]=(r.activityPoints[e.activity]||0)+p; }); Object.entries(state.history).forEach(([date,r])=>{ r.steps=valueFor('steps',date); r.boxBreathingCount=entries(date,'breathing').filter(e=>e.mode==='box').reduce((s,e)=>s+num(e.value),0); r.breathing478Count=entries(date,'breathing').filter(e=>e.mode==='478').reduce((s,e)=>s+num(e.value),0); r.totalPoints=Object.values(r.activityPoints||{}).reduce((a,b)=>a+num(b),0); r.oneUpScore=oneUpScore(date); }); state.points=Object.values(state.history).reduce((s,r)=>s+num(r.totalPoints),0); persist(); }
function oneUpScore(date=todayKey()){ const enabled=Object.keys(activities).filter(id=>state.activitySettings[id]?.enabled); if(!enabled.length) return 0; return Math.round(enabled.reduce((s,id)=>s+activityPercent(id,date),0)/enabled.length); }
function streak(){ const ids=enabledStreakIds(); return ids.length?Math.max(...ids.map(id=>streakInfo(id).current)):0; }
function bestStreak(){ const ids=enabledStreakIds(); return ids.length?Math.max(...ids.map(id=>streakInfo(id).best)):0; }
function addEntry(activity, data){ const e={id:`${Date.now()}-${Math.random().toString(16).slice(2)}`,date:todayKey(),activity,...data}; if(activity==='steps') state.log=state.log.filter(x=>!(x.date===e.date&&x.activity==='steps')); state.log.push(e); recalc(); render(); }
function deleteEntry(id){ state.log=state.log.filter(e=>e.id!==id); recalc(); render(); }
function editEntry(id){ const e=state.log.find(x=>x.id===id); if(!e) return; const v=prompt('Ny værdi', e.value ?? e.hours ?? 0); if(v===null) return; if(e.activity==='sleep') e.hours=num(v); else e.value=num(v); recalc(); render(); }
function compareLastWeek(id){ const now=periodValue(id), last=periodValue(id,day(-7)); if(!last && !now) return 'Ingen sammenligning endnu'; const pct= last ? Math.round((now-last)/last*100) : 100; return pct>=0?`+${pct}% mod sidste uge`:`${pct}% mod sidste uge`; }
function renderToday(){ const score=oneUpScore(), ids=enabledStreakIds(), infos=ids.map(id=>streakInfo(id)), weeklyDone=ids.reduce((s,id)=>s+weeklyConsistency(id).done,0); $('#oneup-score').textContent=score; $('#today-points').textContent=fmt(state.history[todayKey()].totalPoints); $('#header-points').textContent=fmt(state.points); const enabled=Object.keys(activities).filter(id=>state.activitySettings[id]?.enabled); $('#goals-met').textContent=`${enabled.filter(id=>activityPercent(id)>=100).length}/${enabled.length}`; $('#today-streak').textContent=`${streak()} dage`; $('#encouragement').textContent= score>=90?'Du har allerede slået stærkt igennem i dag.':score>=60?'Du er godt i gang – hold rytmen roligt.':'Start med én lille handling. Det tæller.'; const cs=$('#consistency-section'); if(cs) cs.innerHTML=`<div><p class="eyebrow">Konsistens slår perfektion.</p><h3>Konsistensscore: ${consistencyScore()}/100</h3><p>Én god dag mere bygger videre på rytmen.</p></div><div class="mini-metrics"><span>Længste aktive streak: <b>${bestStreak()}</b></span><span>Aktive streaks: <b>${infos.filter(i=>i.current>0).length}/${ids.length}</b></span><span>Ugens gennemførte dage: <b>${weeklyDone}</b></span></div>`; $('#today-activity-cards').innerHTML=enabled.map(activityCard).join(''); }
function activityCard(id){ const a=activities[id], v=periodValue(id), g=goalFor(id), pct=activityPercent(id), pts=state.history[todayKey()].activityPoints?.[id]||0, si=streakInfo(id), wi=weeklyConsistency(id); const streakText=si.current?`${si.current} dage i træk`:'Gennemfør i dag for at fortsætte din streak'; return `<article class="card activity"><div class="card-head"><h3>${a.icon} ${a.name}</h3><strong>${Math.round(pct)}%</strong></div><p class="streak-chip">🔥 ${streakText}</p>${si.protectedToday?'<p class="soft-note">Din rytme er bevaret. En pause ændrer ikke alt.</p>':''}<p class="big">${fmt(v)} ${a.unit}</p><p>Mål: ${fmt(g)} ${a.unit}${a.period==='week'?' pr. uge':''}</p><div class="progress"><span style="width:${pct}%"></span></div><p>${fmt(pts)} point i dag · ${wi.done}/${wi.goal} dage denne uge · ${wi.onTrack?'Du er på kurs til ugens mål.':'Begynd igen i dag.'}</p><button data-quick="${id}">Registrér / redigér</button></article>`; }
function renderActivities(){ $('#activity-manager').innerHTML=Object.entries(activities).map(([id,a])=>{const s=state.activitySettings[id]; return `<article class="card"><div class="card-head"><h3>${a.icon} ${a.name}</h3><label class="switch"><input data-toggle="${id}" type="checkbox" ${s.enabled?'checked':''}/> Aktiv</label></div><p>I dag: ${fmt(valueFor(id))} ${a.unit}</p><label class="field">Personligt mål<input data-goal="${id}" type="number" value="${goalFor(id)}" /></label><div class="streak-settings"><label><input data-streak-enabled="${id}" type="checkbox" ${s.streakEnabled?'checked':''}> Streak til</label><label class="field">Dagligt streak-krav<input data-daily-req="${id}" type="number" value="${dailyRequirementFor(id)}"></label><label class="field">Ugentligt konsistensmål (dage)<input data-weekly-goal="${id}" type="number" min="1" max="7" value="${s.weeklyGoal}"></label><label><input data-protection-enabled="${id}" type="checkbox" ${s.protectionEnabled?'checked':''}> Streak-beskyttelse</label><label><input data-auto-protection="${id}" type="checkbox" ${s.autoProtection?'checked':''}> Brug automatisk streak-beskyttelse</label>${id==='sleep'?sleepSettingsHtml(s):''}</div>${a.auto?'<p class="muted">Automatisk registrering kommer senere.</p>':''}<div class="entry-controls">${entryControls(id)}</div></article>`}).join(''); renderEntryList(); }
function sleepSettingsHtml(s){ const c=s.sleepCriteria||{}; return `<div class="sleep-grid"><p><b>Søvnkriterier</b></p>${[['duration','Minimum søvnlængde'],['interval','Ønsket interval'],['bedtime','Sengetid i vindue'],['wake','Opvågning i vindue'],['screenfree','Skærmfri tid før søvn']].map(([k,l])=>`<label><input data-sleep-criterion="${k}" type="checkbox" ${c[k]?'checked':''}> ${l}</label>`).join('')}<label class="field">Minimum timer<input data-sleep-field="sleepMinHours" type="number" step="0.25" value="${s.sleepMinHours}"></label><label class="field">Interval min/max<input data-sleep-field="sleepMinInterval" type="number" step="0.25" value="${s.sleepMinInterval}"><input data-sleep-field="sleepMaxInterval" type="number" step="0.25" value="${s.sleepMaxInterval}"></label><label class="field">Sengetid ± minutter<input data-sleep-field="bedtimeTarget" type="time" value="${s.bedtimeTarget}"><input data-sleep-field="bedtimeTolerance" type="number" value="${s.bedtimeTolerance}"></label><label class="field">Opvågning ± minutter<input data-sleep-field="wakeTarget" type="time" value="${s.wakeTarget}"><input data-sleep-field="wakeTolerance" type="number" value="${s.wakeTolerance}"></label></div>`; }
function entryControls(id){ if(id==='sleep') return '<input data-sleep-start type="time" value="22:30"><input data-sleep-end type="time" value="06:30"><button data-add="sleep">Registrér søvn</button>'; if(id==='meditation') return '<button data-add="meditation" data-value="5">5</button><button data-add="meditation" data-value="10">10</button><button data-add="meditation" data-value="20">20</button><input data-input="meditation" type="number" placeholder="Min"><button data-add="meditation">Gem</button>'; if(id==='running'||id==='cycling') return `<input data-input="${id}" type="number" placeholder="Minutter"><input data-distance="${id}" type="number" placeholder="Distance valgfri"><button data-add="${id}">Gem</button>`; return `<input data-input="${id}" type="number" placeholder="${activities[id].unit}"><button data-add="${id}">Gem</button>`; }
function renderEntryList(){ $('#entry-list').innerHTML=entries().map(e=>`<li>${activities[e.activity].name}: ${fmt(e.value??e.hours)} ${activities[e.activity].unit} <button data-edit-entry="${e.id}">Ret</button> <button data-delete-entry="${e.id}">Slet</button></li>`).join('')||'<li>Ingen registreringer i dag endnu.</li>'; }
function renderCompetition(){ const type=$('#competition-type'); if(!type.options.length) ['Procent af eget mål','Længste aktuelle streak','Højeste Konsistensscore','Flest gennemførte dage denne uge','Højeste procent af personligt ugemål','Samlede point'].forEach(x=>type.add(new Option(x,x))); const ids=enabledStreakIds(), weekDone=ids.reduce((s,id)=>s+weeklyConsistency(id).done,0), metric=type.value||'Procent af eget mål'; const you=metric.includes('streak')?streak():metric.includes('Konsistens')?consistencyScore():metric.includes('uge')?weekDone:oneUpScore(); const rows=[['Dig',you,'+8',true],['Amina',Math.max(0,you-3),'+4',true],['Jonas',Math.max(0,you-10),'-2',false],['Sofie',Math.max(0,you-15),'+11',true]]; $('#leaderboard').innerHTML=rows.sort((a,b)=>b[1]-a[1]).map((r,i)=>`<li><b>${i+1}. ${r[0]}</b><span>${r[1]} · ${r[3]?'↗':'↘'} ${r[2]}</span></li>`).join(''); $('#self-summary').innerHTML=[`Nuværende streak mod tidligere rekord: ${streak()} / ${bestStreak()}`,`Denne uges konsistens mod sidste uge: ${weeklyTrend(0)}% / ${weeklyTrend(1)}%`,`Denne måned mod forrige måned: ${monthConsistency(0)}% / ${monthConsistency(1)}%`,`Bedste 28-dages periode: ${best28()}%`,`En enkelt pause sletter ikke din fremgang.`].map(t=>`<article class="card">${t}</article>`).join(''); $('#self-ranking').innerHTML=ids.map((id,i)=>`<li><b>${i+1}. ${activities[id].name}</b><span>${weeklyConsistency(id).percent}% af eget ugemål</span></li>`).join(''); }
function weeklyTrend(w){ const ids=enabledStreakIds(); if(!ids.length) return 0; return Math.round(ids.reduce((s,id)=>s+[0,1,2,3,4,5,6].filter(d=>dayComplete(id,day(-(w*7+d)))).length/7*100,0)/ids.length); }
function monthConsistency(m){ const ids=enabledStreakIds(); if(!ids.length) return 0; return Math.round(ids.reduce((s,id)=>s+[...Array(28)].filter((_,i)=>dayComplete(id,day(-(m*28+i)))).length/28*100,0)/ids.length); }
function best28(){ let best=0; for(let o=0;o<120;o++) best=Math.max(best,monthConsistency(Math.floor(o/28))); return best; }
function weeklyScores(){ return [0,1,2,3,4,5,6,7].map(w=>[0,1,2,3,4,5,6].reduce((s,d)=>s+num(state.history[day(-(w*7+d))]?.totalPoints),0)).sort((a,b)=>b-a); }
function renderDevelopment(){ const filter=$('#development-filter'); if(filter.options.length===1) Object.entries(activities).forEach(([id,a])=>filter.add(new Option(a.name,id))); $('#bars-7').innerHTML=[-6,-5,-4,-3,-2,-1,0].map(o=>{const d=day(o), val=filter.value==='all'?oneUpScore(d):activityPercent(filter.value,d); return `<div><span style="height:${val}%"></span><small>${d.slice(5)}</small></div>`}).join(''); $('#bars-4').innerHTML=[3,2,1,0].map(w=>`<div><span style="height:${weeklyTrend(w)}%"></span><small>Uge ${4-w}</small></div>`).join(''); const ids=enabledStreakIds(), infos=ids.map(id=>streakInfo(id)), best=infos.slice().sort((a,b)=>monthConsistencyFor(b.id)-monthConsistencyFor(a.id))[0], need=infos.slice().sort((a,b)=>monthConsistencyFor(a.id)-monthConsistencyFor(b.id))[0]; const sec=$('#streak-development'); if(sec) sec.innerHTML=`<h3>Streaks og konsistens</h3><div class="card-list">${infos.map(i=>`<article class="card"><h4>${activities[i.id].icon} ${activities[i.id].name}</h4><p>Nuværende: ${i.current} dage · Længste: ${i.best} dage · Senest aktiv: ${i.lastActiveDate||'ingen endnu'}</p><p>Uge: ${i.weekly.done}/${i.weekly.goal} dage (${i.weekly.percent}%) · ${i.weekly.onTrack?'Du er på kurs til ugens mål.':'Begynd igen i dag.'}</p><div class="week-dots">${i.weekly.dates.map(d=>`<span class="${dayComplete(i.id,d)?'done':''}">${d.slice(8)}</span>`).join('')}</div></article>`).join('')}</div><p class="info-box">Seneste 4 ugers konsistens vises ovenfor. Bedste stabilitet: ${best?activities[best.id].name:'ingen endnu'}. Mest brug for kontinuitet: ${need?activities[need.id].name:'ingen endnu'}.</p>`; $('#weekly-summary').innerHTML=['Konsistens slår perfektion.','Én god dag mere bygger videre på rytmen.','En enkelt pause sletter ikke din fremgang.'].map(t=>`<article class="card">${t}</article>`).join(''); }
function monthConsistencyFor(id){ return Math.round([...Array(28)].filter((_,i)=>dayComplete(id,day(-i))).length/28*100); }
function renderProfile(){ const fields=[['nickname','Navn eller kaldenavn','text'],['birthYear','Fødselsår','number'],['height','Højde','number'],['weight','Vægt','number'],['sex','Biologisk køn','text'],['country','Bopælsland','text'],['language','Sprog','text'],['units','Enheder','text']]; $('#profile-form').innerHTML=fields.map(([k,l,t])=>`<label class="field">${l}<input name="${k}" type="${t}" value="${state.profile[k]||''}"></label>`).join('')+'<button>Gem profil</button>'; $('#settings-form').innerHTML=['vibration','sounds','voice'].map(k=>`<label><input data-setting="${k}" type="checkbox" ${state.settings[k]?'checked':''}> ${k}</label>`).join('')+'<label class="field">Uge starter<select data-setting="weekStarts"><option value="monday">Mandag</option><option value="sunday">Søndag</option></select></label>'; }
function render(){ recalcSilently(); renderToday(); renderActivities(); renderCompetition(); renderDevelopment(); renderProfile(); bindDynamic(); }
function recalcSilently(){ Object.values(state.history).forEach(r=>{r.activityPoints={};r.totalPoints=0}); state.log.forEach(e=>{const d=effectiveDate(e); const r=state.history[d] ||= {date:d,activityPoints:{}}; const p=pointsForEntry(e); r.activityPoints[e.activity]=(r.activityPoints[e.activity]||0)+p;}); Object.entries(state.history).forEach(([d,r])=>{r.totalPoints=Object.values(r.activityPoints||{}).reduce((s,v)=>s+num(v),0); r.oneUpScore=oneUpScore(d);}); state.points=Object.values(state.history).reduce((s,r)=>s+num(r.totalPoints),0); }
function bindDynamic(){ $$('[data-toggle]').forEach(el=>el.onchange=()=>{state.activitySettings[el.dataset.toggle].enabled=el.checked; persist(); render();}); $$('[data-goal]').forEach(el=>el.onchange=()=>{state.activitySettings[el.dataset.goal].goal=num(el.value); persist(); render();}); $$('[data-daily-req]').forEach(el=>el.onchange=()=>{state.activitySettings[el.dataset.dailyReq].dailyRequirement=num(el.value); persist(); render();}); $$('[data-weekly-goal]').forEach(el=>el.onchange=()=>{state.activitySettings[el.dataset.weeklyGoal].weeklyGoal=clamp(num(el.value),1,7); persist(); render();}); $$('[data-streak-enabled]').forEach(el=>el.onchange=()=>{state.activitySettings[el.dataset.streakEnabled].streakEnabled=el.checked; persist(); render();}); $$('[data-protection-enabled]').forEach(el=>el.onchange=()=>{state.activitySettings[el.dataset.protectionEnabled].protectionEnabled=el.checked; persist(); render();}); $$('[data-auto-protection]').forEach(el=>el.onchange=()=>{state.activitySettings[el.dataset.autoProtection].autoProtection=el.checked; persist(); render();}); $$('[data-sleep-criterion]').forEach(el=>el.onchange=()=>{state.activitySettings.sleep.sleepCriteria[el.dataset.sleepCriterion]=el.checked; persist(); render();}); $$('[data-sleep-field]').forEach(el=>el.onchange=()=>{state.activitySettings.sleep[el.dataset.sleepField]=el.type==='number'?num(el.value):el.value; persist(); render();}); $$('[data-add]').forEach(b=>b.onclick=()=>manualAdd(b.dataset.add,b)); $$('[data-quick]').forEach(b=>b.onclick=()=>showPage('activities')); $$('[data-delete-entry]').forEach(b=>b.onclick=()=>deleteEntry(b.dataset.deleteEntry)); $$('[data-edit-entry]').forEach(b=>b.onclick=()=>editEntry(b.dataset.editEntry)); }
function manualAdd(id,b){ if(id==='sleep'){ const start=$('[data-sleep-start]').value, end=$('[data-sleep-end]').value, [sh,sm]=start.split(':').map(Number), [eh,em]=end.split(':').map(Number); let h=(eh+em/60)-(sh+sm/60); if(h<0) h+=24; addEntry(id,{value:h,hours:h,start,end,sleepDate:todayKey()}); return; } const input=$(`[data-input="${id}"]`); addEntry(id,{value:num(b.dataset.value ?? input?.value), distance:num($(`[data-distance="${id}"]`)?.value), mode:id==='breathing'?document.querySelector('input[name="breathing-mode"]:checked')?.value:undefined}); }
function showPage(id){ $$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===id)); $$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id)); }
function bindStatic(){ $$('[data-nav]').forEach(b=>b.onclick=()=>showPage(b.dataset.nav)); $$('[data-competition]').forEach(b=>b.onclick=()=>{ $$('[data-competition]').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $('#competition-others').hidden=b.dataset.competition!=='others'; $('#competition-self').hidden=b.dataset.competition!=='self';}); $('#create-group').onclick=()=>$('#group-message').textContent='Rigtige grupper og invitationer kræver login og kommer i en senere version.'; $('#profile-form').onsubmit=e=>{e.preventDefault(); new FormData(e.target).forEach((v,k)=>state.profile[k]=v); persist();}; $('#development-filter').onchange=renderDevelopment; $('#competition-type').onchange=renderCompetition; $('#start-breathing').onclick=()=>{ window.breathingTimer=setInterval(()=>addEntry('breathing',{value:1,mode:document.querySelector('input[name="breathing-mode"]:checked')?.value||'box'}), 3000); $('#breathing-label').textContent='Kører';}; $('#stop-breathing').onclick=()=>{clearInterval(window.breathingTimer); $('#breathing-label').textContent='Stoppet';}; }
loadState(); bindStatic(); render(); showPage('today');
if (typeof window !== 'undefined') window.__oneUpTest = { get state(){ return state; }, recalc, oneUpScore, pointsForEntry, activities, requirementMet, streakInfo, weeklyConsistency, consistencyScore, dayComplete, effectiveDate };
if (typeof module !== 'undefined') module.exports={activities,loadState,oneUpScore,pointsForEntry};
